{
 "title": "UNSAM - Sensores",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Wifi RSSI (dbm)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RSSI (dbi)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP8266" }
     ]
    }
   ]
  },
  {
   "title": "WiFi RSSI actual",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 19, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP8266" }
     ]
    }
   ]
  },
  {
   "title": "Sensor uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP8266" }
     ]
    }
   ]
  },
  {
   "title": "Sensor Temperatura [°C]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "degrees celcius [°C]" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP8266" }
     ]
    }
   ]
  },
  {
   "title": "Temperatura promedio",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP8266" }
     ]
    }
   ]
  },
  {
   "title": "Concentración gases en Aire [CO2, CO, NH3]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP8266" }
     ]
    }
   ]
  },
  {
   "title": "Concentración gases promedio",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "co2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP8266" }
     ]
    }
   ]
  },
  {
   "title": "Presion [hPa]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP8266" }
     ]
    }
   ]
  },
  {
   "title": "Presión promedio",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "ESP8266" }
     ]
    }
   ]
  }
 ]
}